# Generated by Django 3.0.8 on 2020-07-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carosel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caroselimg', models.ImageField(blank=True, upload_to='carosel_image')),
                ('des1', models.CharField(max_length=500)),
                ('des2', models.CharField(max_length=500)),
            ],
        ),
    ]
