# Generated by Django 3.0.8 on 2020-07-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donaterimg', models.ImageField(blank=True, upload_to='donater_image')),
                ('donaterdes', models.TextField(max_length=500)),
                ('donaterlocation', models.CharField(max_length=500)),
                ('donatername', models.CharField(max_length=500)),
            ],
        ),
    ]
