# Generated by Django 3.0.8 on 2020-07-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_eventinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinfo',
            name='uploaddate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
