# Generated by Django 3.0.8 on 2020-07-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carosel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caroselimg', models.ImageField(blank=True, upload_to='carosel_image')),
                ('des1', models.CharField(default='', max_length=100)),
                ('des2', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
