# Generated by Django 3.0.8 on 2020-08-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200826_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='/static/images/logo.png', null=True, upload_to='profile_image'),
        ),
    ]
