# Generated by Django 3.0.8 on 2020-08-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200826_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='media/profile_image/silicon-valley-4k-a5-Rjhrs0i.jpg', upload_to='profile_image'),
        ),
    ]
